fuck

diff --git a/nono b/nono
--- a/nono
+++ b/nono
@@ -33,7 +33,7 @@ pkg_open() {
     die "package $PKG does not exist"
 }
 
-pkg_configure() {
+pkg() {
   pkg_open
 
   if [[ -e $BASE/config ]]; then
@@ -74,24 +74,22 @@ pkg_configure() {
     fi
   fi
 
-  if ! fn_exists build; then
-    if [[ ! -z $deps ]]; then
-      PKGTYPE=group
-    else
-      die "empty package: $PKG"
-    fi
-  else
-    if [[ $GIT = yes ]]; then
-      PKGTYPE=git
-    elif [[ ! -z $src ]]; then
-      if [[ -z $type ]]; then
-        die "missing type in package $PKG"
-      fi
+  if [[ $GIT = yes ]]; then
+    PKGTYPE=git
+  elif [[ ! -z $src ]]; then
+    [[ -z $type ]] && \
+      die "missing type in package $PKG"
 
-      PKGTYPE=normal
-    else
-      PKGTYPE=script
-    fi
+    PKGTYPE=normal
+  elif [[ ! -z $deps ]]; then
+    PKGTYPE=group
+  else
+    die "empty package: $PKG"
+  fi
+
+  if [[ $PKGTYPE = normal ]] || [[ $PKGTYPE = git ]]; then
+    [[ -z $files ]] && [[ $DEBUG != yes ]] && \
+      die "missing files setting"
   fi
 
   if [[ -z $ver ]]; then
@@ -112,17 +110,8 @@ pkg_configure() {
 
     unset $FILENAME
     unset $type
-  elif [[ $PKGTYPE = script ]]; then
-    WORK=$SRC/work
-
-    unset $type
   elif [[ $PKGTYPE = group ]]; then
     unset $ver
-  fi
-
-  if [[ $PKGTYPE = normal ]] || [[ $PKGTYPE = git ]]; then
-    [[ -z $files ]] && \
-      die "missing files setting"
   fi
 
   local preffered=$(($(nproc)+1))
@@ -131,22 +120,38 @@ pkg_configure() {
     JOBS=$preffered
   fi
 
-  TARGET="x86_64-linux-musl"
+  ARCH=x86_64
+  TARGET=$ARCH-linux-musl
   HOST=$($CC -dumpmachine)
 
-  CONFIGURE="./configure --prefix=$PREFIX --with-sysroot=$ROOT"
+  DESTDIR=$ROOT
+
+  CONFIGURE="./configure --prefix=$PREFIX"
   MAKE="make -j$JOBS"
-  MAKE_INSTALL="make PREFIX=$PREFIX DESTDIR=$ROOT install"
 
-  export PREFIX=$PREFIX
-  export DESTDIR=$ROOT
+  BIN_PREFIX=$PREFIX/bin
+  BIN=$ROOT$BIN_PREFIX
 
-  [[ -z $OPT ]] && OPT=yes
-  [[ -z $SECURE ]] && SECURE=yes
-  [[ -z $STATIC ]] && STATIC=no
+  ETC_PREFIX=$PREFIX/etc
+  ETC=$ROOT$ETC_PREFIX
+
+  INCLUDE_PREFIX=$PREFIX/include
+  INCLUDE=$ROOT$INCLUDE_PREFIX
+
+  LIB_PREFIX=$PREFIX/lib
+  LIB=$ROOT$LIB_PREFIX
+
+  SHARE_PREFIX=$PREFIX/share
+  SHARE=$ROOT$LIB_PREFIX
+
+  MAN_PREFIX=$SHARE_PREFIX/man
+  MAN=$ROOT$MAN_PREFIX
 
   CFLAGS="-fno-unwind-tables -fno-asynchronous-unwind-tables -Wa,--noexecstack -fno-math-errno"
   LDFLAGS="-Wl,-z,relro,-z,now -Wl,-z,text"
+
+  [[ -z $OPT ]] && OPT=yes
+  [[ -z $SECURE ]] && SECURE=yes
 
   if [[ $OPT = yes ]]; then
     CFLAGS="$CFLAGS -O3 -fstrength-reduce -fthread-jumps -fcse-follow-jumps -fcse-skip-blocks -frerun-cse-after-loop -fexpensive-optimizations -fforce-addr -fomit-frame-pointer"
@@ -164,12 +169,19 @@ pkg_configure() {
     LDFLAGS="$LDFLAGS -static"
   fi
 
+  if [[ -z $SILENT ]]; then
+    if [[ $DEBUG = yes ]]; then
+      SILENT=no
+    else
+      SILENT=yes
+    fi
+  fi
+
   unset $OPT
   unset $SECURE
-  unset $STATIC
 
-  export CFLAGS=$CFLAGS
-  export LDFLAGS=$LDFLAGS
+  export PREFIX DESTDIR
+  export CFLAGS LDFLAGS
 }
 
 pkg_extract() {
@@ -180,37 +192,92 @@ pkg_extract() {
   fi
 
   case $FILENAME in
-  *.zip) unzip $FILENAME -d $WORK ; ;;
-  *.tgz|*.gz) tar xzvf $FILENAME -C $WORK --strip-components 1 ; ;;
-  *.tbz2|*.bz2) tar xjvf $FILENAME -C $WORK --strip-components 1 ; ;;
-  *.xz) tar xf $FILENAME -C $WORK --strip-components 1 ; ;;
+  *.zip) unzip $FILENAME -d $WORK &>/dev/null ; ;;
+  *.tgz|*.gz) tar xzvf $FILENAME -C $WORK --strip-components 1 &>/dev/null ; ;;
+  *.tbz2|*.bz2) tar xjvf $FILENAME -C $WORK --strip-components 1 &>/dev/null ; ;;
+  *.xz) tar xf $FILENAME -C $WORK --strip-components 1 &>/dev/null ; ;;
   esac
 }
 
 pkg_download() {
+  info "downloading $PKG"
+
   if [[ $GIT = yes ]]; then
     cd $BUILD
 
-    git clone $src $NAME
+    if [[ $SILENT = yes ]]; then
+      git clone $src $NAME &>/dev/null
+    else
+      git clone $src $NAME
+    fi
   else
     cd $DL
 
-    wget --no-check-certificate $src -O $FILENAME
+    if [[ $SILENT = yes ]]; then
+      wget --no-check-certificate $src -O $FILENAME &>/dev/null
+    else
+      wget --no-check-certificate $src -O $FILENAME
+    fi
+  fi
+}
+
+pkg_configure() {
+  info "configuring $PKG"
+
+  if ! fn_exists configure; then
+    if [[ -e CMakeLists.txt ]]; then
+      mkdir -p build
+      cd build
+
+      if [[ $SILENT = yes ]]; then
+        cmake .. &>/dev/null
+      else
+        cmake ..
+      fi
+    elif [[ -e configure ]]; then
+      grep -q '--prefix' configure &>/dev/null
+
+      if [ $? -eq 0 ]; then
+        $CONFIGURE
+      else
+        ./configure
+      fi
+    fi
+  else
+    if [[ $SILENT = yes ]]; then
+      configure &>/dev/null
+    else
+      configure
+    fi
   fi
 }
 
 pkg_build() {
-  info "building $NAME"
-
-  cd $WORK
+  info "compiling $NAME"
 
   if [[ -d $PATCHES ]]; then
     for patch in $PATCHES/*; do
-      patch -p1 < $patch
+      patch -p1 < $patch &>/dev/null
     done
   fi
 
-  build
+  if ! fn_exists build; then
+    if [[ -e Makefile ]]; then
+      if [[ $SILENT = yes ]]; then
+        $MAKE &>/dev/null
+      else
+        $MAKE
+      fi
+    else
+      die "no build() in package $PKG"
+    fi
+  else
+    if [[ $SILENT = yes ]]; then
+      build &>/dev/null
+    else
+      build
+    fi
+  fi
 
   local error=yes
 
@@ -218,12 +285,32 @@ pkg_build() {
     [[ -d $file ]] || [[ -e $file ]] && error=no
   done
 
-  [[ $error = yes ]] && \
+  [[ $error = yes && $DEBUG != yes ]] && \
     die "build error on $PKG package"
 }
 
+pkg_package() {
+  info "packaging $NAME"
+
+  if ! fn_exists install; then
+    if [[ -e Makefile ]]; then
+      grep -q 'install:' Makefile &>/dev/null
+
+      if [ $? -eq 0 ]; then
+        $MAKE install
+      fi
+    fi
+  else
+    if [[ $SILENT = yes ]]; then
+      install &>/dev/null
+    else
+      install
+    fi
+  fi
+}
+
 pkg_install() {
-  pkg_configure
+  pkg
 
   if [[ $PKGTYPE = normal ]] || [[ $PKGTYPE = git ]]; then
     if pkg_exists $PKG; then
@@ -251,11 +338,11 @@ pkg_install() {
       echo $PKG >> $PKGS
       return
     fi
+
+    info "installing $NAME"
   fi
 
   if [[ $PKGTYPE = normal ]]; then
-    info "installing package $NAME"
-
     if [[ ! -d $WORK ]] && [[ ! -e $FILE ]]; then
       pkg_download
     fi
@@ -272,11 +359,11 @@ pkg_install() {
       yes | \cp -rf $FILES/* $WORK
     fi
 
-    pkg_build
+    cd $WORK
 
-    if fn_exists install; then
-      install
-    fi
+    pkg_configure
+    pkg_build
+    pkg_package
   elif [[ $PKGTYPE = git ]]; then
     if [[ ! -d $WORK ]]; then
       pkg_download
@@ -289,28 +376,12 @@ pkg_install() {
         yes | \cp -rf $FILES/* $WORK
       fi
 
+      cd $WORK
+
       pkg_build
-
-      if fn_exists install; then
-        install
-      fi
+      pkg_configure
+      pkg_package
     fi
-  elif [[ $PKGTYPE = script ]]; then
-    info "executing script $NAME"
-
-    if [[ -d $FILES ]]; then
-      yes | \cp -rf $FILES/* $WORK
-    fi
-
-    cd $WORK
-
-    if build; then
-      info "script run successfully: $NAME"
-    else
-      info "$NAME script resulted with error"
-    fi
-
-    return
   else
     if pkg_exists $PKG; then
       found=no
@@ -328,7 +399,7 @@ pkg_install() {
 
       return
     else
-      info "installing package group: $NAME"
+      #info "installing package group: $NAME"
 
       for dep in "${deps[@]}"; do
         sh $NONO -i $dep
@@ -337,7 +408,7 @@ pkg_install() {
         fi
       done
 
-      info "package group $PKG installed successfully"
+      #info "package group $PKG installed successfully"
     fi
   fi
 
@@ -358,7 +429,7 @@ pkg_exists() {
 }
 
 pkg_remove() {
-  pkg_configure
+  pkg
 
   if fn_exists remove; then
     if remove; then
