works

diff --git a/src/bin/nono b/src/bin/nono
--- a/src/bin/nono
+++ b/src/bin/nono
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 
 PKG=$2
 
@@ -11,14 +11,17 @@ PKGS=$SRCDIR/pkgs
 PKGDIR=$SRCDIR/pkg/$PKG
 
 BUILDDIR=$SRCDIR/build
+DLDIR=$SRCDIR/dl
 
 PKGFILE=$PKGDIR/build
 
 PATCHES=$PKGDIR/patch
 
-#
+### SCRIPT VARIABLES ###
 
 JOBS=$(nproc)
+
+########################
 
 pkg_open() {
   if [[ ! -d $PKGDIR ]]; then
@@ -30,81 +33,108 @@ pkg_open() {
     exit 1
   fi
   . $PKGFILE
-}
-
-pkg_build() {
   if [[ -z $name ]]; then
     name=$PKG
   fi
+  FULLNAME=$name-$ver
+}
 
-  if [[ -z $ver ]]; then
-    FULLNAME=$name
-  else
-    FULLNAME=$name-$ver
+pkg_extract() {
+  case $FILENAME in
+  *.zip) unzip $FILENAME -d $BUILDDIR ; ;;
+  *.tgz|*.gz) tar xzvf $FILENAME -C $BUILDDIR ; ;;
+  *.tbz2|*.bz2) tar xjvf $FILENAME -C $BUILDDIR ; ;;
+  *.xz) tar xf $FILENAME -C $BUILDDIR ; ;;
+  esac
+}
+
+pkg_download() {
+  FILENAME=$FULLNAME.$type
+
+  if [[ $src == *"git"* ]] && [[ "`basename $src`" != *"."* ]]; then
+    WORK=$BUILDDIR/$name
+
+    cd $BUILDDIR
+
+    if [[ -d $WORK ]]; then
+      git pull
+    else
+      git clone $src $WORK
+    fi
+
+    return
+  elif [[ -z $type ]]; then
+    echo "missing package type in $PKG package"
+    exit 1
   fi
 
   WORK=$BUILDDIR/$FULLNAME
-  FILENAME="`basename $src`"
+  if [[ -d $WORK ]]; then
+    return
+  fi
 
-  if [[ $src == *"github.com"* ]] && [[ $FILENAME != *"."* ]]; then
-    FULLNAME=$name
-    WORK=$BUILDDIR/$FULLNAME
-    git clone $src $WORK
+  cd $DLDIR
+
+  FILE=$DLDIR/$FILENAME
+  if [[ ! -e $FILE ]]; then
+    wget --no-check-certificate $src -O $FILENAME
+  fi
+
+  if [[ -e $FILE ]]; then
+    pkg_extract
   else
-    FILE=$name-$ver.${FILENAME##*.}
-    cd $SRCDIR/dl
-    wget --no-check-certificate $src -O $FILE
-    case $FILE in
-    *.zip) unzip $FILE -d $BUILDDIR ; ;;
-    *.tgz|*.gz) tar xzvf $FILE -C $BUILDDIR ; ;;
-    *.tbz2|*.bz2) tar xjvf $FILE -C $BUILDDIR ; ;;
-    *.xz) xz -d $BUILDDIR ; FILE2=`echo $FILE | sed -e s,.xz,,`; tar xvf $FILE2 -C $BUILDDIR ; ;;
-    esac
+    echo "failed to download, retrying"
+    pkg_download
   fi
-  if [[ ! -d $WORK ]]; then
-    echo "failed to download $name source"
-    exit 1
-  fi
+}
+
+pkg_build() {
   cd $WORK
-  echo "started installing $FULLNAME"
   if [[ -d $PATCHES ]]; then
     for patch in $PATCHES/*; do
       patch -p1 < $patch
+
     done
   fi
   build
-  echo "installation finished: $name"
 }
 
 pkg_install() {
-  if [[ -z $PKG ]]; then
-    echo "provide a package name"
-    exit 1
-  fi
-  if pkg_exists; then
-    echo "package is already installed"
-    exit 1
-  fi
   pkg_open
-  if [[ ! -z $deps ]]; then
+  if pkg_exists $PKG; then
     if [[ -z $src ]]; then
-      echo "installing package group: $PKG"
-    fi
-    for dep in "${deps[@]}"; do
-      sh $ROOT/bin/nono -i $dep
-    done
-    if [[ -z $src ]]; then
-      echo "package group installed: $name"
+      for dep in "${deps[@]}"; do
+        if ! pkg_exists $dep; then
+          sh $ROOT/bin/nono -i $dep
+        fi
+      done
+      return
     else
-      pkg_build
+      echo "$PKG is already installed"
+      exit 1
     fi
+  fi
+  if [[ -z $src ]]; then
+    echo "installing package group: $PKG"
+  else
+    echo "installing package $FULLNAME"
+  fi
+  for dep in "${deps[@]}"; do
+    sh $ROOT/bin/nono -i $dep
+  done
+  if [[ -z $src ]]; then
+    echo "package group installed: $PKG"
+  else
+    pkg_download
+    pkg_build
   fi
   echo $PKG >> $PKGS
+  echo "installation finished: $FULLNAME"
 }
 
 pkg_exists() {
   while read line; do
-    if [[ $line == $PKG ]]; then
+    if [[ $line == $1 ]]; then
       return 0
     fi
   done < $PKGS
@@ -112,16 +142,23 @@ pkg_exists() {
 }
 
 pkg_remove() {
-  if [[ -z $PKG ]]; then
-    echo "provide a package name"
-    exit 1
-  fi
+  while read line; do
+    if [[ $line == $PKG ]]; then
+      # set $line "" from $PKGS
+      return
+    fi
+  done < $PKGS
 }
 
 help() {
   echo "nono -i package: install"
   echo "nono -r package: remove"
 }
+
+if [[ -z $PKG ]]; then
+  echo "provide a package name"
+  exit 1
+fi
 
 case $1 in
 -i) pkg_install ; ;;
